### ISSUE TITLE
Redlisting

### ISSUE THREAD

**Issue by wgilpin** [wgilpin/recruitment-ascee#12]
* BE identify
* FE highlight
e.g
Mail to/from blacklisted alliances
Supers, Titans, Cyno ships
Zero isk contracts
Contracts to reds
WTB contracts
Cyno skills on young char
To many SP for age
Contacts (red)
Red chat channels
Wallet - big transfers
Transactions in red structures
BMs in red space
Clones in red space

**Comment by mcgibbon** [comment]
This is mostly already implemented in existing BE APIs. Could we close this issue and instead put redlisting requirements in descriptions for each separate feature? Or at least, additionally do that (it can be useful to know for example if there isn't currently a useful screen to show clones in red space).

**Comment by wgilpin** [comment]
Yes I'll create a ticket for each kind
