### ISSUE TITLE
Revert recruit action APIs to original

### ISSUE THREAD

**Issue by wgilpin** [wgilpin/recruitment-ascee#35]
recruiter action APIs don't need the recruiter_id as the recruiter is the current user
Currently `/api/recruiter/<int:recruiter_id>/<int:applicant_id>/claim`
Change to `/api/recruits/claim/<int:applicant_id>` to match current FE expectations
also same for 
`api/recruits/escalate`
`api/recruits/escalate`
`api/recruits/deescalate`
`api/recruits/abandon`

**Comment by mcgibbon** [comment]
Closing as you've marked this Done.
